### ISSUE TITLE
Failing to log in

### ISSUE THREAD

**Issue by Ybalrid** [Jman012/Wasserflug-tvOS#13]
![image](https://user-images.githubusercontent.com/1816251/192143138-ab4b6c27-1122-484b-921f-24665e684aac.jpeg)

This happens now when trying to log into floatplane

**Comment by Jman012** [comment]
Thanks! This should be affected by 1.2.2-3 on Test Flight. I've pushed a 1.2.2-4 update to address this. Apologies for the time lost.

**Comment by Ybalrid** [comment]
Running the latest build. I have a different error ![image](https://user-images.githubusercontent.com/1816251/192371300-d39e229c-6140-412c-a05b-5ed55b6e0818.jpeg)

**Comment by Ybalrid** [comment]
And no worries, it's beta *and* unofficial. I expect breakage from time to time 🙂

**Comment by Jman012** [comment]
Ah I see. It looks like some creators have an offline node, but the values are all or partially null:

```json
"offline": {
    "title": null,
    "description": null,
    "thumbnail": null
}
```

I've fixed the error and it should be available as 1.2.2-5 soon.

**Comment by Ybalrid** [comment]
It works for me now!

**Comment by Jman012** [comment]
Great! Otherwise I think this build is stable. Submitting 1.2.2 to the App Store.
