### ISSUE TITLE
Login was successful but an error was encountered

### ISSUE THREAD

**Issue by jamesweston** [Jman012/Wasserflug-tvOS#17]
The app is telling that my login was successful but got the following Application Error

Logging in was successful, but an error was encountered while loading you user profile.
The data couldn't be read because it isn't in the correct format.

dataCorrupted(Swift.DecodingError.Context(codingPath: [_JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "startDate",intValue: nil)], debugDescription: "Date string does not mach format expected by formatter.". underlyingError: nil))

**Comment by Jman012** [comment]
Fixed in d91491dbbd0516f92c9eb4326d7d1c46895ed0f1 and 2cee32ddaec6e551a20e682ade68a85752e8ca53. Thank you for the error message!

I can not push this to the app store currently, but if you're on the Test Flight (see the README) then you should get the latest update in 1.3.0-6 to fix this issue. Happy viewing! Let me know if there are any other errors when logging in now that this (should be) fixed.

**Comment by jamesweston** [comment]
I have updated to Test Flight 1.3.0-6 and getting the same error

**Comment by Jman012** [comment]
Very strange! If you're able to, would you be able to do this on a computer?
1. Visit floatplane.com and login
2. Open up your browser's dev tools, go to the Network tab
3. Refresh the page to populate this tab
4. Filter/search for "subscriptions"
5. View the response JSON

<img width="1166" alt="Screen Shot 2023-01-07 at 10 28 25 AM" src="https://user-images.githubusercontent.com/419958/211165357-714506f9-9f67-4353-ade5-ca2615ae3fc4.png">

I need to see the startDate and endDate value. It appears that it's in a different format than usual.

**Comment by jamesweston** [comment]
Here is the startDate and endDate values.

        "startDate": "2023-01-02T16:26:39.421Z",
        "endDate": "2023-02-02T16:26:39.421Z",

**Comment by Jman012** [comment]
I think I figured it out. I'm guessing your Apple TV is in a locale other than en-US? I had to explicitly mark the date formatter as POSIX in order to be understood properly (not necessarily en-US). Fixed in 10ec89a1b3eab010b5e190bf98792dfc1284611c and version 1.3.0-7. 

I hope this works!

**Comment by jamesweston** [comment]
Yes that has worked I can now login and play videos

**Comment by Jman012** [comment]
Fantastic!! Glad to have helped.
