### ISSUE TITLE
issues with using search

### ISSUE THREAD

**Issue by mayorb13** [Jman012/Wasserflug-tvOS#18]
any time i try to search for a video i get a error like this. 
just with a different Error id
ErrorModel(id: "vzam-v9nj-n56h", errors: [FloatplaneAPIClient. ErrorModelErrorsInner (id: "vzam-v9nj-n56h", name: "paramValidationError", message: Optional ("\"ids\" must contain at least 1 items"), data:

Optional ("rule": AnyCodable("array.min")I))1, message: Optional ("\"ids|" must contain at least 1 items"))

when you put more than a couple of letters in the search trying to find a video
4k apple tv
16.3.2 (20K672)

**Comment by mayorb13** [comment]
and already use the testflight build 1.3.0 (8)

**Comment by Jman012** [comment]
Interesting! I'm seeing the same for some reason. When I use dictation for, e.g., "Dell" when first entering the search screen it works fine. Using the keyboard, "a" is fine, "ab" is fine, but then "abc" and on hits the error until I go back to two letters. 

The error is coming from Floatplane, but indicates Wasserflug isn't sending data correctly. I'll look into this.

**Comment by mayorb13** [comment]
As of right now I no longer have that issue search is working good right now.
