### ISSUE TITLE
Failed to fetch data while accessing a non-LTT channel

### ISSUE THREAD

**Issue by Ybalrid** [Jman012/Wasserflug-tvOS#3]
Hello,

I just enrolled on test flight. The App's really clean, I like it

I have two subscriptions on floatplane, one is LTT, and one is Tyler McVicker (The Passionate Gamer). When clicking on the tab, this appears (with expended details)

![image](https://user-images.githubusercontent.com/1816251/173910437-5d98e428-7565-4e39-b55a-361d0956f972.png)

I have no idea how I can help you debug this further, but the channel has post that do not have thumbnails it seems. It might be causing some API to respond with some JSON that do not have some key/values you are expecting ?

(see posts with no images below)
![image](https://user-images.githubusercontent.com/1816251/173911429-9bde2fd8-cc73-4b4b-bd5b-7285d92a6dd1.png)

**Comment by Jman012** [comment]
Thank you for the pictures! This helps a lot. Yes, I believe that this would be the case (I'm surprised it's possible to not have thumbnails on the videos). 

Normally, the same error would appear on the Home tab as well, but the latest McVicker video is 6 weeks ago, it seems, which wouldn't appear in Home unless you scroll down very far. 

I'll get working on a fix for this. Much appreciated! I'm glad the extra error information I added recently to that screen came in handy so quickly.

**Comment by Jman012** [comment]
This has been addressed in version 1.2.0. This version will release to Test Flight public beta in 1 or 2 days. Please let me know if this fixes the issue for you once it's available and you're able to test it @Ybalrid!

**Comment by Ybalrid** [comment]
Thanks! Will try it out when it's our and let you know so you can close

**Comment by Ybalrid** [comment]
Fiez on the build TestFlight just downloaded! Thanks
