### ISSUE TITLE
Unformatted HTML in video description infobox

### ISSUE THREAD

**Issue by Ybalrid** [Jman012/Wasserflug-tvOS#4]
Here's another small bug, there is some visible `<p>` tags on this video description

https://cdn.discordapp.com/attachments/831003665442799628/986728246479556618/DA87A894-26BE-464B-A0AA-6BC7D005F533.jpg

**Comment by Jman012** [comment]
This has been addressed in version 1.2.0. This version will release to Test Flight public beta in 1 or 2 days. Please let me know if this fixes the issue for you once it's available and you're able to test it, @Ybalrid!

**Comment by Ybalrid** [comment]
1.2 has fixed this, thanks
